# This workflow uploads a file to an AWS S3 bucket using a role to assume.
# AWS recommends using IAM roles instead of ${{USER.ACCESS.KEYS}}.
name: upload to s3 bucket
on: 
  push:
    branches:
      - master
  workflow_dispatch:   # <-- Add this to allow manual triggering

env:
  BUCKET_NAME: "mychirpy"
  AWS_REGION: "ap-southeast-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # Git commits have SHA. This SHA string tells Github which version(commit) of the action to use.
        with:
          role-to-assume: arn:aws:iam::133605102918:role/GitHubOIDC-S3Deploy # This is the IAM role that GitHub Actions will assume to get temporary credentials for AWS.
          role-session-name: github-actions-${{ github.run_id }} # This is a built-in GitHub Actions context variable that’s automatically available during every workflow run. It’s generated fresh for each run and provides a unique identifier for that run, which can be useful for tracking purposes.
          aws-region: ${{ env.AWS_REGION }}
      - name: Debug OIDC token
        run: |
          echo "OIDC token:"
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
      
      # Upload a file to AWS s3
      - name: Copy index.html to s3
        run: |
          ls -la index.html
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/
