name: upload to s3 bucket

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUCKET_NAME: "mychirpy"
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write
  contents: read

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      
      - name: Install dependencies & build the site
        run: |
          bundle install
          bundle exec jekyll build

  authenticate:
    needs: build-site
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::133605102918:role/GithubOIDC-S3
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Fetch caller identity 
        run: aws sts get-caller-identity

  deploy-to-s3:
    needs: authenticate
    runs-on: ubuntu-latest
    steps:
      - name: Copy site to S3
        run: |
          ls -la _site/index.html
          aws s3 cp ./_site/index.html s3://${{ env.BUCKET_NAME }}/index.html
        # Uncomment the next line to upload the full site
          # aws s3 sync ./_site s3://${{ env.BUCKET_NAME }} --delete 